const championships = ["Serie A", "Serie B", "Serie C", "Serie D"];

const teamColors = {
  Flamengo: ["#d71920", "#111111"],
  Palmeiras: ["#006437", "#ffffff"],
  Corinthians: ["#f2f2f2", "#111111"],
  Gremio: ["#00a7e1", "#111111"],
  "Atletico Mineiro": ["#111111", "#ffffff"],
  "Sao Paulo": ["#ffffff", "#d71920"],
  Internacional: ["#d71920", "#ffffff"],
  Cruzeiro: ["#1c5fb8", "#ffffff"],
  Botafogo: ["#111111", "#ffffff"],
  Bahia: ["#0057b8", "#d71920"],
  Vasco: ["#111111", "#ffffff"],
  "Athletico-PR": ["#d71920", "#111111"],
  Ceara: ["#111111", "#ffffff"],
  Sport: ["#d71920", "#f6c13a"],
  Mirassol: ["#f6c13a", "#16803c"],
  Juventude: ["#16803c", "#ffffff"],
  Goias: ["#008c45", "#ffffff"],
  Coritiba: ["#007a3d", "#ffffff"],
  Novorizontino: ["#f6c13a", "#111111"],
  "Vila Nova": ["#d71920", "#ffffff"],
  Avai: ["#1f73d8", "#ffffff"],
  Chapecoense: ["#1b8f3a", "#ffffff"],
  CRB: ["#d71920", "#ffffff"],
  Amazonas: ["#f6c13a", "#111111"],
  "Ponte Preta": ["#111111", "#ffffff"],
  Operario: ["#111111", "#ffffff"],
  Ituano: ["#d71920", "#111111"],
  Brusque: ["#f6c13a", "#d71920"],
  "Sampaio Correa": ["#f6c13a", "#16803c"],
  Londrina: ["#7dd3fc", "#ffffff"],
  Guarani: ["#16803c", "#ffffff"],
  Tombense: ["#d71920", "#ffffff"],
  CSA: ["#0057b8", "#d71920"],
  Nautico: ["#d71920", "#ffffff"],
  Figueirense: ["#111111", "#ffffff"],
  "Botafogo-PB": ["#111111", "#ffffff"],
  Maringa: ["#111111", "#008c45"],
  Caxias: ["#8b0000", "#ffffff"],
  "Ypiranga-RS": ["#16803c", "#f6c13a"],
  Confianca: ["#0057b8", "#ffffff"],
  "Sao Bernardo": ["#f6c13a", "#111111"],
  ABC: ["#111111", "#ffffff"],
  Anapolis: ["#0057b8", "#ffffff"],
  "Londrina-PR": ["#7dd3fc", "#ffffff"],
  Itabaiana: ["#d71920", "#ffffff"],
  "Sao Jose-RS": ["#0057b8", "#ffffff"]
};

const teamsByChampionship = {
  "Serie A": [
    "Flamengo",
    "Palmeiras",
    "Corinthians",
    "Gremio",
    "Atletico Mineiro",
    "Sao Paulo",
    "Internacional",
    "Cruzeiro",
    "Botafogo",
    "Bahia",
    "Vasco",
    "Athletico-PR",
    "Ceara",
    "Sport",
    "Mirassol",
    "Juventude"
  ],
  "Serie B": [
    "Goias",
    "Coritiba",
    "Novorizontino",
    "Vila Nova",
    "Avai",
    "Chapecoense",
    "CRB",
    "Amazonas",
    "Ponte Preta",
    "Operario",
    "Ituano",
    "Brusque",
    "Sampaio Correa",
    "Londrina",
    "Guarani",
    "Tombense"
  ],
  "Serie C": [
    "Amazonas",
    "Ypiranga-RS",
    "Brusque",
    "Maringa",
    "Botafogo-PB",
    "Guarani",
    "Floresta",
    "Paysandu",
    "Barra-SC",
    "Inter de Limeira",
    "Santa Cruz",
    "Figueirense",
    "Ituano",
    "Caxias",
    "Confianca",
    "Volta Redonda",
    "Itabaiana",
    "Ferroviaria",
    "Maranhao",
    "Anapolis"
  ],
  "Serie D": [
    "Nacional-AM",
    "Manaus-AM",
    "Manauara-AM",
    "GAS-RR",
    "Monte Roraima-RR",
    "Sao Raimundo-RR",
    "Independencia-AC",
    "Galvez-AC",
    "Humaita-AC",
    "Porto Velho-RO",
    "Guapore-RO",
    "Araguaina-TO",
    "Gama-DF",
    "Brasiliense-DF",
    "Luverdense-MT",
    "Primavera-MT",
    "Inhumas-GO",
    "Aparecidense-GO",
    "Capital-DF",
    "Ceilandia-DF",
    "Mixto-MT",
    "Operario-MT",
    "Uniao-MT",
    "Goiatuba-GO",
    "Trem-AP",
    "Oratorio-AP",
    "Tuna Luso-PA",
    "Aguia de Maraba-PA",
    "Tocantinopolis-TO",
    "Imperatriz-MA",
    "Sampaio Correa-MA",
    "Moto Club-MA",
    "IAPE-MA",
    "Maracana-CE",
    "Iguatu-CE",
    "Parnahyba-PI",
    "Ferroviario-CE",
    "Tirol-CE",
    "Atletico-CE",
    "Altos-PI",
    "Piaui-PI",
    "Fluminense-PI",
    "ABC-RN",
    "America-RN",
    "Laguna-RN",
    "Sousa-PB",
    "Maguary-PE",
    "Central-PE",
    "Retro-PE",
    "Decisao-PE",
    "Serra Branca-PB",
    "Treze-PB",
    "Lagarto-SE",
    "Sergipe-SE",
    "ASA-AL",
    "CSA-AL",
    "CSE-AL",
    "Jacuipense-BA",
    "Atletico-BA",
    "Juazeirense-BA",
    "Uberlandia-MG",
    "Betim-MG",
    "CRAC-GO",
    "ABECAT-GO",
    "Operario-MS",
    "Ivinhema-MS",
    "Porto-BA",
    "Rio Branco-ES",
    "Vitoria-ES",
    "Real Noroeste-ES",
    "Tombense-MG",
    "Democrata GV-MG",
    "Madureira-RJ",
    "Portuguesa-RJ",
    "America-RJ",
    "Portuguesa-SP",
    "Agua Santa-SP",
    "Pouso Alegre-MG",
    "Nova Iguacu-RJ",
    "Sampaio Correa-RJ",
    "Marica-RJ",
    "XV de Piracicaba-SP",
    "Noroeste-SP",
    "Velo Clube-SP",
    "Cianorte-PR",
    "FC Cascavel-PR",
    "Santa Catarina-SC",
    "Joinville-SC",
    "Guarany de Bage-RS",
    "Sao Luiz-RS",
    "Blumenau-SC",
    "Marcilio Dias-SC",
    "Sao Joseense-PR",
    "Azuriz-PR",
    "Sao Jose-RS",
    "Brasil-RS"
  ]
};

const teams = Object.entries(teamsByChampionship).flatMap(([championship, names]) =>
  names.map((name) => ({ name, championship }))
);

const palette = [
  ["#d71920", "#111111"],
  ["#0057b8", "#ffffff"],
  ["#008c45", "#ffffff"],
  ["#f6c13a", "#111111"],
  ["#7b1fa2", "#ffffff"],
  ["#111111", "#ffffff"],
  ["#00a7e1", "#111111"],
  ["#8b0000", "#f5f7f8"],
  ["#1b8f3a", "#f6c13a"],
  ["#f97316", "#111827"]
];

function hashTeamName(name) {
  return String(name || "").split("").reduce((total, char) => total + char.charCodeAt(0), 0);
}

function colorsForTeam(name) {
  return teamColors[name] || palette[hashTeamName(name) % palette.length];
}

function teamsForChampionship(championship) {
  return teams.filter((team) => team.championship === championship);
}

function isKnownTeam(name) {
  return teams.some((team) => team.name === name);
}

module.exports = {
  championships,
  teamColors,
  teams,
  teamsByChampionship,
  teamsForChampionship,
  isKnownTeam,
  colorsForTeam
};
