const championships = ["Serie A", "Serie B", "Serie C", "Serie D"];

const teamsByChampionship = {
  "Serie A": [
    "Flamengo",
    "Palmeiras",
    "Corinthians",
    "Gremio",
    "Atletico Mineiro",
    "Sao Paulo",
    "Internacional",
    "Cruzeiro",
    "Botafogo",
    "Bahia",
    "Vasco",
    "Athletico-PR",
    "Ceara",
    "Sport",
    "Mirassol",
    "Juventude"
  ],
  "Serie B": [
    "Goias",
    "Coritiba",
    "Novorizontino",
    "Vila Nova",
    "Avai",
    "Chapecoense",
    "CRB",
    "Amazonas",
    "Ponte Preta",
    "Operario",
    "Ituano",
    "Brusque",
    "Sampaio Correa",
    "Londrina",
    "Guarani",
    "Tombense"
  ],
  "Serie C": [
    "Amazonas",
    "Ypiranga-RS",
    "Brusque",
    "Maringa",
    "Botafogo-PB",
    "Guarani",
    "Floresta",
    "Paysandu",
    "Barra-SC",
    "Inter de Limeira",
    "Santa Cruz",
    "Figueirense",
    "Ituano",
    "Caxias",
    "Confianca",
    "Volta Redonda",
    "Itabaiana",
    "Ferroviaria",
    "Maranhao",
    "Anapolis"
  ],
  "Serie D": [
    "Nacional-AM",
    "Manaus-AM",
    "Manauara-AM",
    "GAS-RR",
    "Monte Roraima-RR",
    "Sao Raimundo-RR",
    "Independencia-AC",
    "Galvez-AC",
    "Humaita-AC",
    "Porto Velho-RO",
    "Guapore-RO",
    "Araguaina-TO",
    "Gama-DF",
    "Brasiliense-DF",
    "Luverdense-MT",
    "Primavera-MT",
    "Inhumas-GO",
    "Aparecidense-GO",
    "Capital-DF",
    "Ceilandia-DF",
    "Mixto-MT",
    "Operario-MT",
    "Uniao-MT",
    "Goiatuba-GO",
    "Trem-AP",
    "Oratorio-AP",
    "Tuna Luso-PA",
    "Aguia de Maraba-PA",
    "Tocantinopolis-TO",
    "Imperatriz-MA",
    "Sampaio Correa-MA",
    "Moto Club-MA",
    "IAPE-MA",
    "Maracana-CE",
    "Iguatu-CE",
    "Parnahyba-PI",
    "Ferroviario-CE",
    "Tirol-CE",
    "Atletico-CE",
    "Altos-PI",
    "Piaui-PI",
    "Fluminense-PI",
    "ABC-RN",
    "America-RN",
    "Laguna-RN",
    "Sousa-PB",
    "Maguary-PE",
    "Central-PE",
    "Retro-PE",
    "Decisao-PE",
    "Serra Branca-PB",
    "Treze-PB",
    "Lagarto-SE",
    "Sergipe-SE",
    "ASA-AL",
    "CSA-AL",
    "CSE-AL",
    "Jacuipense-BA",
    "Atletico-BA",
    "Juazeirense-BA",
    "Uberlandia-MG",
    "Betim-MG",
    "CRAC-GO",
    "ABECAT-GO",
    "Operario-MS",
    "Ivinhema-MS",
    "Porto-BA",
    "Rio Branco-ES",
    "Vitoria-ES",
    "Real Noroeste-ES",
    "Tombense-MG",
    "Democrata GV-MG",
    "Madureira-RJ",
    "Portuguesa-RJ",
    "America-RJ",
    "Portuguesa-SP",
    "Agua Santa-SP",
    "Pouso Alegre-MG",
    "Nova Iguacu-RJ",
    "Sampaio Correa-RJ",
    "Marica-RJ",
    "XV de Piracicaba-SP",
    "Noroeste-SP",
    "Velo Clube-SP",
    "Cianorte-PR",
    "FC Cascavel-PR",
    "Santa Catarina-SC",
    "Joinville-SC",
    "Guarany de Bage-RS",
    "Sao Luiz-RS",
    "Blumenau-SC",
    "Marcilio Dias-SC",
    "Sao Joseense-PR",
    "Azuriz-PR",
    "Sao Jose-RS",
    "Brasil-RS"
  ]
};

const teams = Object.entries(teamsByChampionship).flatMap(([championship, names]) =>
  names.map((name) => ({ name, championship }))
);

function teamsForChampionship(championship) {
  return teams.filter((team) => team.championship === championship);
}

function isKnownTeam(name) {
  return teams.some((team) => team.name === name);
}

module.exports = {
  championships,
  teams,
  teamsByChampionship,
  teamsForChampionship,
  isKnownTeam
};
